[package]
name = "chibi"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = "2.3.1"
async-stream = "0.3.6"
cpal = "0.15.3"
iced = { version = "0.13.1", features = ["image"] }
iced_futures = "0.13.2"
image = "0.25.5"
